### ISSUE TITLE
logs not getting logged in file during runtime

### ISSUE THREAD

**Issue by indraksha** [brmmm3/fastlogging#6] opened 2021-06-25 12:11 UTC
I am writing logs to text file but it remains empty until the program stops or logfile is rotated

**Comment by brmmm3** [comment] 2021-06-25 12:13
Are you using the latest bugfix version? The before had this issue.

**Comment by indraksha** [comment] 2021-06-25 12:25
yes , i am using version 0.9.5

**Comment by brmmm3** [comment] 2021-06-25 12:27
Can you provide an example code you are using?

**Comment by indraksha** [comment] 2021-06-25 12:33
from fastlogging import LogInit
import time
logger = LogInit(domain='new_logger',pathName='testLog.log',maxSize=800000000,backupCnt=2, console=False, colors=False)
t=time.time()
for i in range(1,100000):
    logger.info(f'writing {i}th line in log file')
    time.sleep(0.01)


I am testing with this code

**Comment by brmmm3** [comment] 2021-07-05 06:03
Sorry for the late response. The issue is fixed in 0.9.6.

**Closed by brmmm3** 2021-07-05 06:03 UTC

**Comment by indraksha** [comment] 2021-07-06 12:23
Yes , its getting updated in real time in 0.9.6 but its working only if we use 'useThreads=True' in LogInit() argument

Thanks a lot for the fix
